apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: cronworkflow
  namespace: development
spec:
  schedule: 00 7 * * *
  timezone: "Europe/Amsterdam"
  concurrencyPolicy: "Replace"
  workflowSpec:
    entrypoint: main
    workflowTemplateRef:
      name: workflowtemplate
      

# yaml-language-server: $schema=https://raw.githubusercontent.com/argoproj/argo-workflows/master/api/jsonschema/schema.json
