apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: daily-
commonLabels:
  app: daily

bases:
- ../resources

patches:
- patch: |
    - op: replace
      path: /spec/templates/0/container/command
      value: [ /opt/bin/daily-batch-report.py ]
  target:
    kind: WorkflowTemplate
    name: workflowtemplate
- patch: |
    - op: replace
      path: /spec/schedule
      value: "00 7 * * *"
  target:
    kind: CronWorkflow
    name: cronworkflow

# yaml-language-server: $schema=https://json.schemastore.org/kustomization.json