apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-limit
  namespace: dev-argocd
spec:
  destination:
    namespace: hhue
    server: https://kubernetes.default.svc
  project: dev-argocd
  source:
    path: hello-limit
    repoURL: https://github.com/hhue13/argo-examples.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
      prune: false
      syncOptions:
        - CreateNamespace=false
        - RespectIgnoreDifferences=true
        - ApplyOutOfSyncOnly=true