apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: development
namePrefix: dev-
commonLabels:
  env: dev

bases:
- ../../base

configMapGenerator:
  - name: environment-configmap
    behavior: merge
    literals:
      - EMAIL_TO=me@acme.com

# yaml-language-server: $schema=https://json.schemastore.org/kustomization.json