apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: nightly-
commonLabels:
  app: nightly

bases:
- ../resources

patches:
- patch: |
    - op: replace
      path: /spec/templates/0/container/command
      value: [ /opt/bin/nightly-report.py ]
  target:
    kind: WorkflowTemplate
    name: workflowtemplate
- patch: |
    - op: replace
      path: /spec/schedule
      value: "00 22 * * 1-5"
  target:
    kind: CronWorkflow
    name: cronworkflow

# yaml-language-server: $schema=https://json.schemastore.org/kustomization.json
