apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production
namePrefix: prod-
commonLabels:
  env: prod

bases:
- ../../base

configMapGenerator:
  - name: environment-configmap
    behavior: merge
    literals:
      - MS_TEAMS_WEBHOOK=""

# yaml-language-server: $schema=https://json.schemastore.org/kustomization.json
