# kustomization.yml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configurations:
  - ../../../kustomizeconfig.yml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: bin-configmap
    files:
      - "../../daily-report.py"
      - "../../helpers.py"
      - "../../nightly-report.py"
  - name: environment-configmap
    literals:
      - ARGO_SECURE=true
      - ARGO_INSECURE_SKIP_VERIFY=true
      - ARGO_HTTP1=true
      - ENVIRONMENT=base
      - ARGO_SERVER=argo-play.apps.fpx.azure.rabodev.com:443

bases:
  - daily-report
  - nightly-report

# yaml-language-server: $schema=https://json.schemastore.org/kustomization.json
